version: '3'
  
services:
  redis-streams-monitor:
    container_name: redis-streams-monitor
    image: chrnola/redis-streams-exporter:latest
    networks:
      - backend
    ports:
      - "3002:3000"
    environment:
      REDIS_CONNECTION_STRING: "${REDIS_CONNECTION_STRING}"
      REDIS_STREAM_KEY: "${REDIS_STREAM_KEY}"
      REDIS_POLL_INTERVAL_MS: "${REDIS_POLL_INTERVAL_MS}"
      APP_ENABLE_VERBOSE_LOGGING: "${APP_ENABLE_VERBOSE_LOGGING}"
      PROMETHEUS_PORT: "${PROMETHEUS_PORT}"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - backend
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    depends_on:
      - redis-streams-monitor
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - backend
    depends_on:
    - prometheus

networks:
  backend:
    driver: bridge