global:
  scrape_interval:     10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus
  - job_name: redis-streams-exporter1
    static_configs:
      - targets: ['redis-streams-exporter1:3000']
        labels:
          instance: redis-streams-exporter
  - job_name: redis-streams-exporter2
    static_configs:
      - targets: ['redis-streams-exporter2:3000']
        labels:
          instance: redis-streams-exporter
