{
 "title": "Redis stream monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "redis_stream_length",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_stream_length{}" }
   ]
  },
  {
   "title": "redis_stream_latest_id",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_stream_latest_id{}" }
   ]
  },
  {
   "title": "redis_stream_consumer_group_last_delivered_id",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_stream_consumer_group_last_delivered_id{}"
    }
   ]
  },
  {
   "title": "redis_stream_consumer_pending_messages_total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_stream_consumer_pending_messages_total{}"
    }
   ]
  },
  {
   "title": "redis_stream_consumer_pending_messages_total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_stream_consumer_pending_messages_total{}"
    }
   ]
  }
 ]
}